<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9e9bb048-0485-41cf-ad46-bd04cc184214</testSuiteGuid>
   <testCaseLink>
      <guid>19c4a2ca-debb-4d51-a81a-327f9ae3a1a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC1</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>fc83bcef-6b4d-4f89-890f-17932957f638</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/WSAT Test Data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>fc83bcef-6b4d-4f89-890f-17932957f638</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>campaign</value>
         <variableId>26fa8cb2-aa06-4595-b3ef-4ba82cc557ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fc83bcef-6b4d-4f89-890f-17932957f638</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>event</value>
         <variableId>da40da05-1c1e-4da1-a0f5-a4c41cf03659</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
